config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index, :show, :edit, :update]

  resources :wikis do
    post 'collaborators/:user_id', as: :collaborator, to: "collaborators#create"
    delete 'collaborators/:user_id', as: :collaborators, to: "collaborators#destroy"
   end

  resources :charges, only: [:new, :create] do
    post '/cancel_subscription' => 'charges#cancel_subscription', as: :cancel_subscription
  end

  authenticated :user do
    root 'wikis#index', as: :authenticated_root
  end

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable #:confirmable

  has_many :wikis, dependent: :destroy, foreign_key: "user_id"
  has_many :collaborators
  has_many :wiki_collaborations, through: :collaborators, source: :wiki

  after_initialize :set_standard_role , :if => :new_record?

  before_save { self.email = email.downcase if email.present? }

  validates :password, presence: true, length: { minimum: 6 }, on: :create

  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 254 }

  enum role: [:standard, :premium, :admin]


  def change_user_role(new_role)
   update_attribute(:role, new_role)
  end

  def cancel_privates
    @user = self
    @user.wikis.each { |wiki| wiki.set_as_public }
  end

  def downgrade
   self.change_user_role(0)
   self.cancel_privates
  end
  private
  def set_standard_role
    self.role ||= :standard
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update] # probably want to keep using this

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # # GET /users/1
  # # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # # PATCH/PUT /users/1
  # # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:role, :email)
    end

end

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h2>Blocipedia Users</h2>
        </div>
          <div class="panel-body">
            <div class="panel-group">
              <% @users.each do |user| %>
                <div class="panel panel-default">
                  <div class="panel-body">
                    <div class="row">
                      <div class="col-lg-5 col-xs-8">
                        <h4>
                          <%= link_to "#{user.email.split('@')[0].titleize}", user, class: "" %>
                          <% if user.admin? %>
                            <span class="label label-admin"><i class="fa fa-power-off" aria-hidden="true"></i> Admin</span>
                          <% elsif user.premium? %>
                            <span class="label label-premium"><i class="fa fa-trophy" aria-hidden="true"></i> Premium</span>
                          <% end %>
                        </h4>
                      </div>
                      <div class="col-xs-4 pull-right">
                        <h4>Total Wikis Posted: <span class="text-primary"><%= user.wikis.count %></span></h4>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-12 col-sm-12 col-xs-12">
      <div class="panel panel-sm panel-primary">
        <div class="panel-heading wikis-index-heading">
          <h2 class="profile-heading">
            <% if @user.premium? %>
              <span class="label label-premium profile-label"><i class="fa fa-trophy" aria-hidden="true"></i></span>
            <% end %>
            <%= @user.email.split("@")[0].titleize %>'s Profile</h2>
          <span style="text-align:right; position:inherit; float:right; margin-top:-30px; margin-bottom:10px;">
            <% if @user == current_user || current_user.admin? %>
              <%= link_to 'Edit Profile', edit_user_registration_path(@user), class: 'btn btn-warning' %>
            <% else %>
            <%= link_to 'Back', :back, class: "btn btn-warning" %>
            <% end %>
          </span>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-lg-8 col-md-6 col-sm-12">
              <div class="well">
                <h3>Account details:</h3>
                <h4>Email: <%= @user.email %></h4>
                <h4>Membership status:
                  <% if @user.admin? %>
                    <span class="label label-admin"><i class="fa fa-power-off" aria-hidden="true"></i> Admin</span>
                  <% elsif @user.premium? %>
                    <span class="label label-premium"><i class="fa fa-trophy" aria-hidden="true"></i> Premium</span>
                  <% else %>
                    <%= @user.role %>
                  <% end %>
                </h4>
              </div>
              <% if @user == current_user || current_user.admin? %>
                <div class="well" style="text-align:center;">
                  <% if @user.standard? %>
                    <h3 class="text-primary">Want to post private Wikis?</h3>
                    <br>
                    <%= link_to 'Upgrade to Premium', new_charge_path, class: "btn btn-success btn-lg" %>
                  <% elsif @user.premium? %>
                       <%= link_to 'Cancel Premium Membership', charge_cancel_subscription_path(@user), class: 'btn btn-default', method: :post, data: {confirm: "Canceling your membership will cause all of your private wikis to become public, are you sure you want to cancel?"}%>
                  <% end %>
                </div>
              <% end %>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12">
              <div class="panel panel-info">
                <div class="panel-heading"><h3>User Stats:</h3></div>
                <div class="panel-body">
                  <h4>Member for: <span class="text-primary"><%= time_ago_in_words(@user.created_at) %></span></h4>
                </div>
                <div class="panel-body">
                  <h4>Last Login: <span class="text-primary">
                    <% if @user.last_sign_in_at != nil  %>
                     <%= time_ago_in_words(@user.last_sign_in_at) %> ago.
                    <% end %>
                  </span></h4>
                </div>
                <div class="panel-body">
                  <h4>Total Blocipedia Logins: <span class="text-primary"><%= @user.sign_in_count %></span></h4>
                </div>
                <div class="panel-body">
                  <h4>Total Wikis Posted: <span class="text-primary"><%= @user.wikis.count %></span></h4>
                </div>
              </div>
            </div>
          </div>
          <div class="panel panel-default users-wiki-heading">
            <h3>User's Wikis: </h3>
          </div>
          <div class="panel-group">
            <% @user.wikis.each do |wiki| %>
              <div class="panel panel-info">
                <div class="panel-heading wiki-heading"><h3>
                <span><i class="fa fa-black-tie" aria-hidden="true"></i> <%= wiki.title %></span></h3>
                <h4 class="gray-text">By:
                  <%= link_to(user_path(wiki.user))  do %>
                    <%= wiki.user.email.split("@")[0].titleize %>
                  <% end %>
                <% if wiki.user.admin? %>
                  <span class="label label-admin"><i class="fa fa-power-off" aria-hidden="true"></i> Admin</span>
                  <% elsif wiki.user.premium? %>
                  <span class="label label-premium"><i class="fa fa-trophy" aria-hidden="true"></i> Premium</span>
                <% end %>
                </h4>
                  <% if wiki.private %>
                    <span class="label label-danger"> Private</span>
                  <% else %>
                    <span class="label label-success"> Public</span>
                  <% end %>
                  <% if wiki.created_at == wiki.updated_at %>
                  <span class="label label-info">Posted: <span class="gray-text"><%= time_ago_in_words(wiki.created_at) %> ago</span></span>
                  <% else %>
                    <span class="label label-info">Posted: <span class="gray-text"><%= time_ago_in_words(wiki.created_at) %> ago</span></span>
                    <span class="label label-warning">Updated: <span class="gray-text"><%= time_ago_in_words(wiki.updated_at) %> ago</span></span>
                  <% end %>
                </div>
                <div class="panel-body wiki-panel-body">
                    <div class="panel ">
                      <!-- <div class="panel-body wiki-panel-inner-body">
                        <% if wiki.private? && wiki.user != current_user && !current_user.admin? %>
                           <h3><span class="label label-danger">This Wiki is set to private..</span></h3>
                        <% else %>
                          <p><%= wiki.body %></p>
                        <% end %>
                      </div> -->
                    </div>
                </div>
                <div class="panel-footer wiki-footer">
                  <% if policy(wiki).destroy? %>
                  <div class="dropdown wiki-edit-dropdown">
                    <button class="btn btn-primary dropdown-toggle btn-sm" type="button" data-toggle="dropdown"><i class="fa fa-pencil" aria-hidden="true"></i> Edit
                    <span class="caret"></span></button>
                    <ul class="dropdown-menu dropdown-menu-right">
                      <li><%= link_to 'Edit Wiki', edit_wiki_path(wiki), class: " menu-edit-wiki" %></li>
                      <li><%= link_to 'Destroy', wiki, method: :delete, data: { confirm: 'Are you sure?' }, class: "menu-destroy-wiki" %></li>
                    </ul>
                  </div>
                  <% end %>
                  <%= link_to '<i class="fa fa-black-tie" aria-hidden="true"></i> View Wiki'.html_safe, wiki, class: "btn btn-primary btn-sm btn-view-wiki" %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <div class="panel-footer wikis-index-footer" style="text-align:center;">
          <%= link_to 'New Wiki', new_wiki_path, class: 'btn btn-success btn-block' %>
        </div>
      </div>
    </div>
  </div>
</div>