config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index, :show, :edit, :update]

  resources :wikis do
    post 'collaborators/:user_id', as: :collaborator, to: "collaborators#create"
    delete 'collaborators/:user_id', as: :collaborators, to: "collaborators#destroy"
   end

  resources :charges, only: [:new, :create] do
    post '/cancel_subscription' => 'charges#cancel_subscription', as: :cancel_subscription
  end

  authenticated :user do
    root 'wikis#index', as: :authenticated_root
  end

  root 'welcome#index'

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators

  after_initialize(:set_default_private, {if: :new_record?})

    validates :title, length: { minimum: 5 }, presence: true
    validates :body, length: { minimum: 20 }, presence: true
    validates :user, presence: true
    # validates :user, presence: true

  # scope :visible_to, -> (user){user ? where("private is null or private=? or user_id=?",false, user.id).uniq : where(private:false)}
  # scope :public_wikis, -> {where(private:false)}
  # scope :private_wikis, -> {where(private:true)}
  # scope :my_wikis, -> (user){where(user_id:user)}

  # default_scope {order('lower(title)')}
  default_scope { order(updated_at: :desc) }

  def set_default_private
    self.private ||= false
  end

  def set_as_public
    self.update_attribute(:private, false)
  end

  def public?

    !self.private

  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_wiki, only: [:show, :edit, :update, :destroy]
  #before_action :authorize_private_wikis, only: [:new, :edit, :update. :create]

  # GET /wikis
  def index
    @wikis = policy_scope(Wiki)
    # @wikis = Wiki.all
  end

  # GET /wikis/1
  def show
    @wiki = Wiki.find(params[:id])
  end

  # GET /wikis/new
  def new
    @wiki = Wiki.new
  end

  # GET /wikis/1/edit
  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  # POST /wikis
  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user


    if @wiki.save
      redirect_to @wiki, notice: 'Wiki was successfully created.'
    else
      flash[:alert] = "Something is wrong, please try again."
      render :new
    end
  end

  # PATCH/PUT /wikis/1
  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.update(wiki_params)
      redirect_to @wiki, notice: 'Wiki was successfully updated.'
    else
      flash[:alert] = "Something is wrong, please try again."
      render :edit
    end
  end

  # DELETE /wikis/1
  def destroy
    @wiki.destroy
    authorize @wiki
    redirect_to wikis_url, notice: 'Wiki was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wiki
      @wiki = Wiki.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def wiki_params
      params.require(:wiki).permit(:title, :body, :private, :user_id)
    end

    def authorize_private_wikis
      @wiki = Wiki.find(params[:id])
      params.require(:wiki).permit(:private)
      @user = current_user
      unless wiki.user.premium? == current_user || current_user.admin?
        flash[:alert] = "You must be a premium user to do that."
        redirect_to [wiki, wiki]
      end
    end
end

app/helpers/wikis_helper.rb
module WikisHelper

  # def verified_to_view(user, wiki)
  #
  #   if wiki.private?
  #     if wiki.user || current_user.admin? ||
  #
  #
  #    && wiki.user != current_user && !current_user.admin? || wiki.collaborators.include?(current_user)
  #
  # end

end

app/views/wikis/_form.html.erb
<%= form_for(@wiki) do |f| %>
  <% if @wiki.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wiki.errors.count, "error") %> prohibited this wiki from being saved:</h2>

      <ul>
      <% @wiki.errors.full_messages.each do |message| %>
      <div class="alert alert-danger alert-dismissable">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <li><%= message %></li>
      </div>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title, class: "control-label" %><br>
    <%= f.text_field :title, class: "form-control", placeholder: "Awe-inspiring Wiki Title.." %>
  </div>
  <div class="field form-group">
    <%= f.label :body, class: "control-label" %><br>
    <%= f.text_area :body, cols: "30", rows: "10", class: "form-control", placeholder: "Ground Breaking Wiki Content..." %>
  </div>
  <% if current_user.admin? || current_user.premium? %>
  <div class="field form-group">
    <!-- <%= f.label :private, type: "hidden" %><br> -->
    <span class="label label-warning private-form-label">Make this Wiki private <span class="badge private_badge"><%= f.check_box :private, class: "private_check form-control"%></span></span>
  </div>
  <% end %>
  <!-- <div class="field form-group">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id, class: "form-control"  %>
  </div> -->
  <div class="actions">
    <%= f.submit class:"btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-12 col-sm-12">
      <div class="panel panel-sm panel-primary">
        <div class="panel-heading"><h1>Editing Wiki </h1>
            <span style="text-align:right; position:inherit; float:right; margin-top:-65px; margin-bottom:10px;"><%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i> Delete Wiki'.html_safe, @wiki, method: :delete, data: { confirm: 'Are you sure? This action can not be undone.' }, class: "btn btn-danger" %></span>
        </div>
        <div class="panel-body">
          <%= render 'form' %>
            <% if @wiki.private? || @wiki.users.include?(current_user) %>
              <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#collaborators_modal">Edit Collaborators</button>
            <%end%>
        </div>
        <div class="panel-footer" style="text-align:right;">
          <%= link_to 'View Wiki', @wiki, data: { confirm: 'Are you sure? Any edits you have made will be lost.' }, class: "btn btn-primary" %>
            <%= link_to 'Cancel'.html_safe, wikis_path, data: { confirm: 'Are you sure? Any edits you have made will be lost.' }, class: "btn btn-danger btn-lg" %>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="collaborators_modal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h2> Manage Collaborators</h2>
      </div>
      <div class="modal-body">
        <% User.all.each do |user| %>
          <% if user.id != current_user.id %>
            <div class="row">
              <% if @wiki.users.include?(user) %>
                <div class="col-lg-6 pull-right">
                  <%= "#{user.email}(#{user.id})" %>
                  <%= link_to "remove as collaborator", wiki_collaborators_path(@wiki, user), class: 'btn btn-danger', method: :delete%>
                </div>
              <%else%>
                <div class="col-lg-6">
                  <%= "#{user.email}(#{user.id})" %>
                  <%= button_to "add as collaborator", wiki_collaborators_path(@wiki.id, user.id), class: 'btn btn-success'%>
                </div>
              <%end%>
            </div>
          <%end%>
        <%end%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/wikis/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-12 col-sm-12 col-xs-12">
      <div class="panel panel-sm panel-primary">
        <div class="panel-heading wikis-index-heading">
          <h2>Wikis</h2>
            <span style="text-align:right; position:inherit; float:right; margin-top:-30px; margin-bottom:10px;"><%= link_to 'New Wiki', new_wiki_path, class: 'btn btn-success btn-sm' %></span>
        </div>
        <div class="panel-body">
          <div class="panel-group">
            <% @wikis.each do |wiki| %>
              <div class="panel panel-info">
                <div class="panel-heading wiki-heading"><h3>
                <span><i class="fa fa-black-tie" aria-hidden="true"></i> <%= wiki.title %></span></h3>
                <h4 class="gray-text">By:
                  <%= link_to(user_path(wiki.user))  do %>
                  <%= wiki.user.email.split("@")[0].titleize %>
                  <% end %>
                <% if wiki.user.admin? %>
                  <span class="label label-admin"><i class="fa fa-power-off" aria-hidden="true"></i> Admin</span>
                  <% elsif wiki.user.premium? %>
                  <span class="label label-premium"><i class="fa fa-trophy" aria-hidden="true"></i> Premium</span>
                <% end %>
                </h4>
                  <% if wiki.private %>
                    <span class="label label-danger"> Private</span>
                  <% else %>
                    <span class="label label-success"> Public</span>
                  <% end %>
                  <% if wiki.created_at == wiki.updated_at %>
                    <span class="label label-info">Posted: <span class="gray-text"><%= time_ago_in_words(wiki.created_at) %> ago</span></span>
                  <% else %>
                    <span class="label label-info">Posted: <span class="gray-text"><%= time_ago_in_words(wiki.created_at) %> ago</span></span>
                    <span class="label label-warning">Updated: <span class="gray-text"><%= time_ago_in_words(wiki.updated_at) %> ago</span></span>
                  <% end %>
                </div>
                <div class="panel-body wiki-panel-body">
                    <div class="panel ">
                      <div class="panel-body wiki-panel-inner-body">
                            <p><%= markdown(wiki.body) %></p>
                      </div>
                    </div>
                </div>
                <div class="panel-footer wiki-footer">
                  <% if policy(wiki).destroy? %>
                  <div class="dropdown wiki-edit-dropdown">
                    <button class="btn btn-primary dropdown-toggle btn-sm" type="button" data-toggle="dropdown"><i class="fa fa-pencil" aria-hidden="true"></i> Edit
                    <span class="caret"></span></button>
                    <ul class="dropdown-menu dropdown-menu-right">
                      <li><%= link_to 'Edit Wiki', edit_wiki_path(wiki), class: " menu-edit-wiki" %></li>
                      <li><%= link_to 'Destroy', wiki, method: :delete, data: { confirm: 'Are you sure?' }, class: "menu-destroy-wiki" %></li>
                    </ul>
                  </div>
                  <% end %>
                  <%= link_to '<i class="fa fa-black-tie" aria-hidden="true"></i> View Wiki'.html_safe, wiki, class: "btn btn-primary btn-sm btn-view-wiki" %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <div class="panel-footer wikis-index-footer" style="text-align:center;">
          <%= link_to 'New Wiki', new_wiki_path, class: 'btn btn-success btn-block' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/wikis/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-12 col-sm-12">
      <div class="panel panel-sm panel-primary">
        <div class="panel-heading"><h1>New Wiki</h1></div>
        <div class="panel-body">
          <%= render 'form' %>
        </div>
        <div class="panel-footer" style="text-align:right;">
            <%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i> Cancel'.html_safe, wikis_path, data: { confirm: 'Are you sure? This wiki has not been saved. All progress will be lost.' }, class: "btn btn-danger btn-lg" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/wikis/show.html.erb
<div class="container-fluid">
  <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-12 col-xs-12">
    <div class="panel panel-info">
      <div class="panel-heading wiki-heading">
        <h3><span><i class="fa fa-black-tie" aria-hidden="true"></i> <%= @wiki.title %></span></h3>
        <h4 class="gray-text">By:
          <%= link_to(user_path(@wiki.user))  do %>
            <%= @wiki.user.email.split("@")[0].titleize %>
          <% end %>
          <% if @wiki.user.admin? %>
            <span class="label label-admin"><i class="fa fa-power-off" aria-hidden="true"></i> Admin</span>
            <% elsif @wiki.user.premium? %>
            <span class="label label-premium"><i class="fa fa-trophy" aria-hidden="true"></i> Premium</span>
          <% end %>
        </h4>
        <% if @wiki.private %>
          <span class="label label-danger"> Private</span>
        <% else %>
          <span class="label label-success"> Public</span>
        <% end %>
        <% if @wiki.created_at == @wiki.updated_at %>
          <span class="label label-info">Posted: <span class="gray-text"><%= time_ago_in_words(@wiki.created_at) %> ago</span></span>
        <% else %>
          <span class="label label-info">Posted: <span class="gray-text"><%= time_ago_in_words(@wiki.created_at) %> ago</span></span>
          <span class="label label-warning">Updated: <span class="gray-text"><%= time_ago_in_words(@wiki.updated_at) %> ago</span></span>
        <% end %>
      </div>
      <div class="panel-body wiki-panel-body">
          <div class="panel ">
            <div class="panel-body wiki-panel-inner-body">
              <% if @wiki.private? && @wiki.user != current_user && !current_user.admin? %>
                 <h3><span class="label label-danger">This @wiki is set to private..</span></h3>
              <% else %>
                <p><%= markdown(@wiki.body) %></p>
              <% end %>
            </div>
          </div>
      </div>
      <div class="panel-footer wiki-footer">
        <% if policy(@wiki).destroy? %>
          <div class="dropdown @wiki-edit-dropdown">
            <button class="btn btn-primary dropdown-toggle btn-sm" type="button" data-toggle="dropdown"><i class="fa fa-pencil" aria-hidden="true"></i> Edit
            <span class="caret"></span></button>
            <ul class="dropdown-menu dropdown-menu-right">
              <li><%= link_to 'Edit Wiki', edit_wiki_path(@wiki), class: " menu-edit-wiki" %></li>
              <li><%= link_to 'Destroy', @wiki, method: :delete, data: { confirm: 'Are you sure?' }, class: "menu-destroy-wiki" %></li>
            </ul>
          </div>
        <% end %>
        <%= link_to 'Back', :back, class: "btn btn-warning" %>
        <%= link_to '<i class="fa fa-black-tie" aria-hidden="true"></i> View All Wiki\'s'.html_safe, wikis_path, class: "btn btn-primary btn-sm btn-view-wiki" %>
      </div>
    </div>
  </div>
</div>