config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index, :show, :edit, :update]

  resources :wikis do
    post 'collaborators/:user_id', as: :collaborator, to: "collaborators#create"
    delete 'collaborators/:user_id', as: :collaborators, to: "collaborators#destroy"
   end

  resources :charges, only: [:new, :create] do
    post '/cancel_subscription' => 'charges#cancel_subscription', as: :cancel_subscription
  end

  authenticated :user do
    root 'wikis#index', as: :authenticated_root
  end

  root 'welcome#index'

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     description: "Premium Membership - #{current_user.email}",
     amount: Amount.default
   }
  end

  class Amount
    def self.default
      @amount = 15_00
    end
  end

  def create
    @user = current_user
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id, # Note -- this is NOT the user_id in your app
      amount: Amount.default,
      description: "Premium Membership - #{current_user.email}",
      currency: 'usd'
    )
    @user.change_user_role(1)
    flash[:notice] = "Thank you for signing up, #{current_user.email}! You are now a premium member."
    redirect_to user_path(current_user)

    # Stripe will send back CardErrors, with friendly messages
    # when something goes wrong.
    # This `rescue block` catches and displays those errors.
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
  end

  def cancel_subscription
    @user = current_user
    @user.downgrade
    flash[:notice] = "#{current_user.email}, your premium membership has been cancled. All of your private wikis are now public."
    redirect_to user_path(current_user)
  end



end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/new.html.erb
 <div class="container">
   <div class="row">
     <div class="col-lg-6 col-lg-offset-3 col-md-12 col-sm-12">
       <div class="panel panel-sm panel-primary">
         <div class="panel-heading"><h2><i class="fa fa-lock" aria-hidden="true"></i> Secure Payment - Premium Membership</h2></div>
         <div class="panel-body">
           <div class="row">
             <div class="col-xs-12">
               <h3>Please select your perfered payment method:</h3>
               <br>
             </div>
             <div class="col-lg-12 col-md-12 col-sm-12">
               <%= form_tag charges_path do %>
                 <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
               <% end %>
             </div>
           </div>
         </div>
         <div class="panel-footer" style="text-align:center;">
         </div>
       </div>
     </div>
     <div class="col-sm-1 col-sm-offset-1"><h3 class="text-primary">
       <i class="fa fa-cc-visa" aria-hidden="true"></i>
     </h3></div>
     <div class="col-sm-1 col-sm-offset-1"><h3 class="text-primary">
       <i class="fa fa-cc-mastercard" aria-hidden="true"></i>
     </h3></div>
     <div class="col-sm-1 col-sm-offset-1"><h3 class="text-primary">
       <i class="fa fa-cc-discover" aria-hidden="true"></i>
     </h3></div>
     <div class="col-sm-1 col-sm-offset-1"><h3 class="text-primary">
       <i class="fa fa-cc-amex" aria-hidden="true"></i>
     </h3></div>
     <div class="col-sm-1 col-sm-offset-1"><h3 class="text-primary">
       <i class="fa fa-cc-stripe" aria-hidden="true"></i>
     </h3></div>
   </div>
 </div>